name: Security Scan

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install python-owasp-zap-v2 pynessus

    - name: Run Security Scan
      run: python path/to/your/script.py  # Update with the actual path to your script

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: security-reports
        path: reports_*  # Update with the actual directory pattern

